#!/bin/sh
#
# fixup        Prepares network and dropbear
#

umask 077

start() {
	chown root:root /etc/dropbear/dropbear_*_host_key
	chmod 600 /etc/dropbear/dropbear_*_host_key
}
stop() {
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

